version: "3.7"

services:
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TICTON_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${TICTON_DB_PASSWORD}
    ports:
      - ${TICTON_DB_PORT}:27017
    volumes:
      - ./.volumes/db:/data/db
